/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_evanpatton_raptortest_Raptor */

#ifndef _Included_com_evanpatton_raptortest_Raptor
#define _Included_com_evanpatton_raptortest_Raptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_evanpatton_raptortest_Raptor
 * Method:    parse
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_evanpatton_raptortest_Raptor_parse
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
