/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_librdf_rasqal_ResultSet_Iterator */

#ifndef _Included_org_librdf_rasqal_ResultSet_Iterator
#define _Included_org_librdf_rasqal_ResultSet_Iterator
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
