/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_librdf_raptor_RaptorWorld */

#ifndef _Included_org_librdf_raptor_RaptorWorld
#define _Included_org_librdf_raptor_RaptorWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_librdf_raptor_RaptorWorld
 * Method:    newWorld
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_librdf_raptor_RaptorWorld_newWorld
  (JNIEnv *, jclass);

/*
 * Class:     org_librdf_raptor_RaptorWorld
 * Method:    freeWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_librdf_raptor_RaptorWorld_freeWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
