/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_librdf_rasqal_QueryExecutor */

#ifndef _Included_org_librdf_rasqal_QueryExecutor
#define _Included_org_librdf_rasqal_QueryExecutor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_librdf_rasqal_QueryExecutor
 * Method:    executeQuery
 * Signature: (Lorg/librdf/raptor/RaptorWorld;[BJ)J
 */
JNIEXPORT jlong JNICALL Java_org_librdf_rasqal_QueryExecutor_executeQuery
  (JNIEnv *, jclass, jobject, jbyteArray, jlong);

/*
 * Class:     org_librdf_rasqal_QueryExecutor
 * Method:    getMessages
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_librdf_rasqal_QueryExecutor_getMessages
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
