/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_librdf_rasqal_Query_Type */

#ifndef _Included_org_librdf_rasqal_Query_Type
#define _Included_org_librdf_rasqal_Query_Type
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
